---

stages:
  - build-image
  - test-image

image: docker
services:
- docker:dind

# set up dev environment - run for every branch except master
.dev_env: &dev_env
  environment: dev
  variables:
    env_tag: 'dev'
  only:
    - master

# set varialbes
variables:
  GIT_SSL_NO_VERIFY: "true"
  container_image: "insulae-ci-runner"
  my_registry: "shinxir"

#build and push dev image
build-dev-image:
  stage: build-image
  <<: *dev_env
  script:
    - docker login registry.gitlab.com -u "${my_registry}" -p "${GITLABREGISTRY}"
    - echo "Building container image $container_image"
    - docker build -f ubuntu-20.04.dockerfile -t "${container_image}" -t registry.gitlab.com/insulae_dev/insulae-ci-runner .
    - docker run "${container_image}"
    - docker tag "${container_image}" "${my_registry}"/"${container_image}":"${env_tag}"
    - docker push "${my_registry}"/"${container_image}":"${env_tag}"
    - docker push registry.gitlab.com/insulae_dev/insulae-ci-runner:"${env_tag}"


