---

stages:
  - build-image
  - test-image

image: docker
services:
- docker:dind

# set up dev environment - run for every branch except master
.dev_env: &dev_env
  environment: dev
  variables:
    env_tag: 'dev'
  only:
    - master

# set varialbes
variables:
  GIT_SSL_NO_VERIFY: "true"
  container_image: "insulae-ci-runner"
  my_registry: "shinxir"

#build and push dev image
build-dev-image:
  stage: build-image
  <<: *dev_env
  script:
    - docker login -u "${my_registry}" -p "${DOCKERHUBPW}"
    - echo "Building container image $container_image"
    - docker build -t "${container_image}" .
    - docker run "${container_image}"
    - docker tag "${container_image}" "${my_registry}"/"${container_image}":"${env_tag}"
    - docker push "${my_registry}"/"${container_image}":"${env_tag}"


