name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
    - uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

    - name: Build the Docker image
      # run: docker build . --file Dockerfile --tag insulae-ci-runner:$(date +%s)
      # run: docker builder prune --all docker build --tag insulae-ci-runner:$(date +%s) .
    - run: docker builder prune --all docker build --no-cache --pull -t insulae-ci-runner:$(date +%s) .
